#ifndef GUITextures_h
#define GUITextures_h

#include <microsim/MSLink.h>

enum GUITexture {
    TEXTURE_LINKDIR_STRAIGHT = MSLink::LINKDIR_STRAIGHT ,
    TEXTURE_LINKDIR_TURN = MSLink::LINKDIR_TURN,
    TEXTURE_LINKDIR_LEFT = MSLink::LINKDIR_LEFT,
    TEXTURE_LINKDIR_RIGHT = MSLink::LINKDIR_RIGHT,
    TEXTURE_LINKDIR_PARTLEFT = MSLink::LINKDIR_PARTLEFT,
    TEXTURE_LINKDIR_PARTRIGHT = MSLink::LINKDIR_PARTRIGHT,
    TEXTURE_MAX
};


#endif
