sonar.organization=eclipse
sonar.projectKey=org.eclipse.sumo

# relative paths to source directories. More details and properties are described
# in https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/
sonar.sources=.
# activating checks for the GitHub workflows and Dockerfiles triggers a lot of warnings for pip install like
# "Using dependencies without locking resolved versions is security-sensitive"
sonar.exclusions=**/*.java,**/*.flow,**/*CSHARP_wrap.cxx,**/*JAVA_wrap.cxx,**/*PYTHON_wrap.cxx,\
  .github/workflows/*,build_config/docker/*,**/pyproject.toml,**/config.h,\
  src/foreign/fontstash/*,src/foreign/nlohmann/*,src/foreign/zstr/*
sonar.host.url=https://sonarcloud.io
sonar.python.version=3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14

sonar.issue.ignore.multicriteria=c1,c2,c3,c4,p1,p2,p3,p4,p5
# insecure paths read from files
sonar.issue.ignore.multicriteria.c1.ruleKey=cpp:S2083
sonar.issue.ignore.multicriteria.c1.resourceKey=src/**/*
# input from files going into logging
sonar.issue.ignore.multicriteria.c2.ruleKey=c:S5145
sonar.issue.ignore.multicriteria.c2.resourceKey=src/**/*
sonar.issue.ignore.multicriteria.c3.ruleKey=cpp:S5145
sonar.issue.ignore.multicriteria.c3.resourceKey=src/**/*
# constructing modal dialogs and immediately discarding the object e.g. GNEWarningBasicDialog
sonar.issue.ignore.multicriteria.c4.ruleKey=cpp:S5184
sonar.issue.ignore.multicriteria.c4.resourceKey=src/netedit/**/*.cpp
# insecure paths in python tools coming from command line input
sonar.issue.ignore.multicriteria.p1.ruleKey=pythonsecurity:S8701
sonar.issue.ignore.multicriteria.p1.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.p2.ruleKey=pythonsecurity:S8703
sonar.issue.ignore.multicriteria.p2.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.p3.ruleKey=pythonsecurity:S8704
sonar.issue.ignore.multicriteria.p3.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.p4.ruleKey=pythonsecurity:S8705
sonar.issue.ignore.multicriteria.p4.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.p5.ruleKey=pythonsecurity:S8707
sonar.issue.ignore.multicriteria.p5.resourceKey=**/*.py
