#!/usr/bin/env python
"""
@file    rebuildConstants.py
@author  Daniel.Krajzewicz@dlr.de
@date    2009-07-24
@version $Id$

This script extracts definitions from <SUMO>/src/traci-server/TraCIConstants.h
 and builds an according constants definition python file "traciconstants.py".

Copyright (C) 2009 DLR/TS, Germany
All rights reserved
"""
import os, string, sys, StringIO

dirname = os.path.dirname(sys.argv[0])
fdo = open(os.path.join(dirname, "traciconstants.py"), "w")
print >> fdo, """
\"\"\"
@file    traciconstants.py

This script contains TraCI constant definitions from <SUMO>/src/traci-server/TraCIConstants.h
generated by "rebuildConstants.py", see there

Copyright (C) 2009 DLR/TS, Germany
All rights reserved
\"\"\"


"""

fdi = open(os.path.join(dirname, "..", "..", "src", "traci-server", "TraCIConstants.h"))
started = False
for line in fdi:
	if started:
		if line.find("#endif")>=0:
			started = False
			continue
		if line.find("#define ")>=0:
			vals = line.split(" ")
			line = vals[1] + " = " + vals[2]
		line = line.replace("//", "#")
		fdo.write(line)
	if line.find("#define TRACICONSTANTS_H")>=0:
		started = True
fdi.close()
fdo.close()
