# Build the docker image locally:       docker build -f docker/Dockerfile.manylinux . -t manylinux2014_aarch64
# Store the docker image in a tar file: docker save -o manylinux2014_aarch64.tar manylinux2014_aarch64
# Transfer it with scp and reload:      docker load -i manylinux2014_aarch64.tar
# how to build it for x64:              docker build --build-arg platform=manylinux2014_x86_64 -f docker/Dockerfile.manylinux . -t manylinux2014_x64
# how to build it for manylinux_2_28:   docker build --build-arg platform=manylinux_2_28_x86_64 -f docker/Dockerfile.manylinux . -t manylinux_2_28_x64
# if you build the image for arm on x64, you need to run the following instructions once:
# sudo apt-get install qemu binfmt-support qemu-user-static
# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
# then you can build:                   docker build --platform=linux/arm64/v8 -f docker/Dockerfile.manylinux . -t manylinux2014_aarch64

ARG platform=manylinux2014_aarch64
FROM quay.io/pypa/${platform}
ARG platform
LABEL description="Dockerfile for a container to build ${platform} python packages"

COPY install_dependencies.sh /opt/install_dependencies.sh
RUN cd /opt && ./install_dependencies.sh
