#ifndef GUIIcons_h
#define GUIIcons_h

enum GUIIcon {
    ICON_APP = 0,
    ICON_OPEN,
    ICON_RELOAD,
    ICON_SAVE,
    ICON_CLOSE,

    ICON_START,
    ICON_STOP,
    ICON_STEP,

    ICON_MICROVIEW,
    ICON_LAGGRVIEW,

    ICON_RECENTERVIEW,
    ICON_SHOWLEGEND,
    ICON_ALLOWROTATION,

    ICON_LOCATEJUNCTION,
    ICON_LOCATEEDGE,
    ICON_LOCATEVEHICLE,

    ICON_COLOURVEHICLES,
    ICON_COLOURLANES,
    ICON_SHOWGRID,
    ICON_SHOWTOOLTIPS,
    ICON_SHOWFULLGEOM,

    ICON_YES,
    ICON_NO,

    ICON_FLAG,
    ICON_FLAG_PLUS,
    ICON_FLAG_MINUS,

    ICON_WINDOWS_CASCADE,
    ICON_WINDOWS_TILE_VERT,
    ICON_WINDOWS_TILE_HORI,

    ICON_MANIP,
    ICON_CAMERA,

    ICON_SPEEDLIMIT_020KMH,
    ICON_SPEEDLIMIT_040KMH,
    ICON_SPEEDLIMIT_060KMH,
    ICON_SPEEDLIMIT_080KMH,
    ICON_SPEEDLIMIT_100KMH,
    ICON_SPEEDLIMIT_120KMH,
    ICON_SPEEDLIMIT_140KMH,
    ICON_SPEEDLIMIT_160KMH,
    ICON_SPEEDLIMIT_180KMH,
//    ICON_SPEEDLIMIT_200KMH,

    ICON_MAX

};

#endif
