# Maximum number of allowed redirects.
max_redirects = 20

# Proceed for server connections considered insecure (invalid TLS).
insecure = true

# Remap URI matching pattern to different URI.
remap = ['%7B%7BVersion%7D%7D 1.23.1']

# Exclude URLs and mail addresses from checking (supports regex).
exclude = ['%7B%7BSource%7D%7D', '^https://sumo\.dlr\.de/generate-documentation\.php', '^https://sumo\.dlr\.de/xsd/SCHEMA_FILE',
           '^https://web\.archive\.org/web/', '^https://doi\.org/10', 'https://www\.researchgate\.net/publication/',
           '^https://elib\.dlr\.de/cgi/', '^https://wiki\.openstreetmap\.org/', '^https://wiki\.dlr\.de/']

# avoid agressive filtering (error code 401)
user_agent = "curl/8.4.0"
headers = ["accept=text/html", "accept-language=en-US,en;q=0.9"]
