site_name: SUMO Documentation
site_url: https://sumo.dlr.de/docs/
repo_url: https://github.com/eclipse-sumo/sumo/
edit_uri: edit/main/docs/web/docs/
site_description: SUMO Documentation
use_directory_urls: false
dev_addr: 127.0.0.1:8000
#docs_dir: docs
#site_dir: site
copyright: "Copyright &copy; 2001-2024 German Aerospace Center (DLR) and others."

nav:
  - Documentation: index.md
  - Tutorials: Tutorials/index.md
  - FAQ: FAQ.md
  - Downloads: Downloads.md
  - Publications: Publications.md
  - Developer: Developer/index.md
  - ChangeLog: ChangeLog.md
  - Contact: https://eclipse.dev/sumo/contact/

theme:
  name: mkdocs
  custom_dir: theme/
  shortcuts:
    help: 191     # ?
    search: 83    # s
    edit: 69      # e

validation:
  links:
    absolute_links: info
    anchors: warn
    unrecognized_links: warn

plugins:
  - git-revision-date:
      as_datetime: true
  - unused_files:
      dir: images
      excluded_files:
        - apple-touch-icon.png
        - favicon.ico
        - image-facebook.jpg
        - mkdocs-grid.png
        - sumo-logo.png
        - sumo-logo.svg
  - macros
  - redirects:
      redirect_maps:
          "ChangeLog/index.md" : "ChangeLog.md"
          "Contact.md" : "https://eclipse.dev/sumo/contact/"

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tilde
  - meta
  - pymdownx.keys
  - footnotes
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
      separator: "_"
      baselevel: 1
  - pymdownx.magiclink:
      provider: github
  - mdx_gh_links:
      user: eclipse-sumo
      repo: sumo
  - plantuml_markdown
  - codehilite

extra:
    Version: 1.21.0
    ReleaseDate: 10.10.2024

    AdditionalFile: '[*additional-file*](/docs/sumo.html#format_of_additional_files)'
    AdditionalFiles: '[*additional-files*](/docs/sumo.html#format_of_additional_files)'
    DT_2DBoundingBox: '[*&lt;2D-BOUNDING_BOX&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_2DPosition: '[*&lt;2D-POSITION&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_BOOL: '[*&lt;BOOL&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_Color: '[*&lt;COLOR&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_FILE: '[*&lt;FILE&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_FLOAT: '[*&lt;FLOAT&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_IDList: '[*&lt;ID&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_INT: '[*&lt;INT&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_NET: '[*&lt;NETWORK_FILE&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_PATH: '[*&lt;PATH&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_PROJ_DEF: '[*&lt;PROJ_DEFINITION&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_Routes: '[*&lt;ROUTES_FILE&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_STR: '[*&lt;STRING&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_STR_LIST: '[*&lt;STRING&lbrack; &rbrack;&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    DT_TIME: '[*&lt;TIME&gt;*](/docs/Basics/Notation.html#referenced_data_types)'
    Outdated: '<div style="background: #801010; padding: .5em; border: 1px dashed #ffcc44; margin-right:10px; margin-left:10px; color: #ffffff">This information is outdated.</div>'
    Source: 'https://github.com/eclipse-sumo/sumo/blob/main/'
    SUMO: '***&lt;SUMO_HOME&gt;***'
    SUMOUSERConference: '[SUMO User Conference](https://eclipse.dev/sumo/conference)'
