# Eclipse SUMO, Simulation of Urban MObility; see https://eclipse.dev/sumo
# Copyright (C) 2026-2026 German Aerospace Center (DLR) and others.
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the Eclipse
# Public License 2.0 are satisfied: GNU General Public License, version 2
# or later which is available at
# https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later

# @file    simulation_manager.py
# @author  Ralf Leibold
# @author  Michael Behrisch
# @date    2026-06-23

import jupedsim_pb2
import dataclasses
import os
import sys
import threading
from pathlib import Path

import jupedsim as jps
import shapely
from google.protobuf import json_format

sys.path.insert(0, os.path.dirname(__file__))


# Needed to dump agent parameters in debug mode to generate a standalone script.
_TUPLE_KEYS = ("position", "orientation", "desired_direction", "velocity")


def _geometry_construction(polygon):
    """Render a stored shapely.Polygon back into its construction code."""
    boundary = list(polygon.exterior.coords)
    holes = [list(interior.coords) for interior in polygon.interiors]
    return f"shapely.Polygon({boundary!r}, holes={holes!r})"


def _render_model_kwargs(param_dict):
    return ", ".join(f"{key}={value!r}" for key, value in param_dict.items())


def _render_agent_kwargs(param_dict):
    parts = []
    for key, value in param_dict.items():
        if key == "journey_id":
            parts.append(f"journey_id=journey_{int(value)}")
        elif key == "stage_id":
            parts.append(f"stage_id=stage_{int(value)}")
        elif key in _TUPLE_KEYS and isinstance(value, list):
            parts.append(f"{key}={tuple(value)!r}")
        else:
            parts.append(f"{key}={value!r}")
    return ", ".join(parts)


class SimulationScript:
    def __init__(self, script_file_name):
        self.written_geometries = set()  # geometry_id already known?
        self._file = open(script_file_name, "w")
        self.write(
            '"""Auto-generated by the JuPedSim gRPC server (--debug).',
            "",
            f'Run with: python {script_file_name}"""',
            "import jupedsim as jps",
            "import shapely",
            "",
        )

    def write(self, *lines):
        # Flush after every record so a hard crash still leaves a usable script.
        if not lines:
            return
        self._file.write("\n".join(lines) + "\n")
        self._file.flush()


def _type_name(annotation):
    """Render a type annotation as a readable string (e.g. "tuple[float, float]")."""
    if isinstance(annotation, str):  # PEP 563 string annotation
        return annotation
    if isinstance(annotation, type):
        return annotation.__name__
    return str(annotation)


def _describe_params(cls):
    """Extract name, type and default value of data classes."""
    params = []
    if not dataclasses.is_dataclass(cls):
        return params
    for field in dataclasses.fields(cls):
        if field.default is not dataclasses.MISSING:
            default = repr(field.default)
        elif field.default_factory is not dataclasses.MISSING:
            default = repr(field.default_factory())
        else:
            default = ""
        params.append(jupedsim_pb2.ModelParameter(
            name=field.name,
            type=_type_name(field.type),
            default=default,
        ))
    return params


class SimulationManager:
    def __init__(self, debug=False, sqlite=False):
        self._geometry_id_counter = 0
        self._simulation_id_counter = 0
        self._geometries = {}  # geometry_id -> shapely.Polygon
        self._simulations = {}  # sim_id -> jps.Simulation
        self._agents = {}  # agent_id -> simulation_id
        self._stages = {}  # stage_id (waypoint or exit) -> simulation_id
        self._journeys = {}  # journey_id -> simulation_id
        self._lock = threading.Lock()
        self._debug = debug
        self._scripts = {}  # sim_id -> SimulationScript
        self._sqlite = sqlite

    def _script(self, simulation_id):
        """Return the reproduction script for a simulation, or None if disabled."""
        return self._scripts.get(simulation_id)

    def _write_geometry(self, script, geometry_id):
        """Emit a geometry's construction once per simulation script."""
        if geometry_id not in script.written_geometries:
            script.written_geometries.add(geometry_id)
            script.write(
                f"geometry_{geometry_id} = "
                f"{_geometry_construction(self._geometries[geometry_id])}"
            )

    def generate_geometry_id(self):
        with self._lock:
            self._geometry_id_counter += 1
            return self._geometry_id_counter

    def generate_simulation_id(self):
        with self._lock:
            self._simulation_id_counter += 1
            return self._simulation_id_counter

    def create_geometry(self, boundary, obstacles):
        if len(boundary) < 3:
            return None, "boundary needs at least 3 points"
        for obstacle in obstacles:
            if len(obstacle) < 3:
                return None, "each obstacle needs at least 3 points"
        geometry_id = self.generate_geometry_id()
        self._geometries[geometry_id] = shapely.Polygon(
            boundary, holes=obstacles
        )
        return dict(geometry_id=geometry_id), None

    def switch_geometry(self, simulation_id, geometry_id):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        if (geometry := self._geometries.get(geometry_id, None)) is None:
            return None, f"geometry ID {geometry_id} unknown"
        try:
            simulation.switch_geometry(geometry)
        except RuntimeError as e:
            return None, str(e)
        if (script := self._script(simulation_id)) is not None:
            self._write_geometry(script, geometry_id)
            script.write(f"simulation.switch_geometry(geometry_{geometry_id})")
        return {}, None

    def create_simulation(
        self, geometry_id, model_class, delta_t, parameters=None
    ):
        if delta_t <= 0:
            return None, "delta_t must be positive"
        if (geometry := self._geometries.get(geometry_id, None)) is None:
            return None, f"geometry ID {geometry_id} unknown"
        if not model_class:
            return None, "model_class must not be empty"
        if (jps_model_cls := getattr(jps, model_class, None)) is None:
            return None, f"model {model_class} does not exist in JuPedSim"
        param_dict = {}
        if parameters is not None:
            param_dict = json_format.MessageToDict(parameters)
        # The model class is a dataclass; unset parameters keep their defaults.
        try:
            model = jps_model_cls(**param_dict)
        except TypeError as e:
            return None, str(e)
        simulation_id = self.generate_simulation_id()
        writer = None
        if self._sqlite:
            writer = jps.SqliteTrajectoryWriter(
                output_file=Path(f"simulation{simulation_id}.sqlite"),
                every_nth_frame=10,
                commit_every_nth_write=1,
            )
        self._simulations[simulation_id] = jps.Simulation(
            model=model,
            geometry=geometry,
            dt=delta_t,
            trajectory_writer=writer,
        )
        if self._debug:
            script_file = self._debug
            if self._scripts:
                file_name = os.path.join(os.path.dirname(self._debug), f"simulation{simulation_id}.py")
            script = SimulationScript(script_file)
            self._scripts[simulation_id] = script
            self._write_geometry(script, geometry_id)
            script.write(
                f"model = jps.{model_class}({_render_model_kwargs(param_dict)})",
                f"simulation = jps.Simulation(model=model, geometry=geometry_{geometry_id}, dt={delta_t!r})\n"
            )
        return dict(simulation_id=simulation_id), None

    def get_model_classes(self):
        # Reflect model classes and their parameters from JuPedSim.
        models = []
        for name in sorted(dir(jps)):
            cls = getattr(jps, name)
            if not isinstance(cls, type) or not dataclasses.is_dataclass(cls):
                # Model classes have to be data classes
                continue
            agent_params_name = f"{name}AgentParameters"
            agent_params_cls = getattr(jps, agent_params_name, None)
            if agent_params_cls is None:
                # Only a model class if a corresponding "{model_class}AgentParameters" exist as well
                continue
            models.append(jupedsim_pb2.ModelClassInfo(
                model_class=name,
                model_parameters=_describe_params(cls),
                agent_parameters=_describe_params(agent_params_cls),
            ))
        return dict(models=models), None

    def create_agent(self, simulation_id, agent_model_class, parameters):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        if not agent_model_class:
            return None, "agent_model_class must not be empty"
        if not hasattr(jps, agent_model_class):
            return None, f"model {agent_model_class} does not exist in JuPedSim"
        param_dict = {}
        if parameters is not None:
            param_dict = json_format.MessageToDict(parameters)

        # Convert float values back to int where needed for native constructors
        for key in ("journey_id", "stage_id"):
            if key in param_dict and isinstance(param_dict[key], float):
                param_dict[key] = int(param_dict[key])

        # Create model parameters
        jps_model_param_cls = getattr(
            jps, f"{agent_model_class}AgentParameters"
        )
        agent_params = jps_model_param_cls(**param_dict)
        agent_id = simulation.add_agent(agent_params)
        self._agents[agent_id] = simulation_id
        if (script := self._script(simulation_id)) is not None:
            script.write(
                f"agent_{agent_id} = simulation.add_agent("
                f"jps.{agent_model_class}AgentParameters("
                f"{_render_agent_kwargs(param_dict)}))"
            )
        return dict(agent_id=agent_id), None

    def remove_agents(self, simulation_id, agent_ids):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        # mark_agent_for_removal defers actual removal to the next iterate.
        for agent_id in agent_ids:
            try:
                simulation.mark_agent_for_removal(agent_id)
            except RuntimeError as e:
                return None, str(e)
        if (script := self._script(simulation_id)) is not None:
            script.write(*(
                f"simulation.mark_agent_for_removal(agent_{agent_id})"
                for agent_id in agent_ids
            ))
        return {}, None

    def switch_agent_journey(
        self, simulation_id, agent_id, journey_id, stage_id
    ):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        try:
            simulation.switch_agent_journey(agent_id, journey_id, stage_id)
        except RuntimeError as e:
            return None, str(e)
        if (script := self._script(simulation_id)) is not None:
            script.write(
                f"simulation.switch_agent_journey(agent_{agent_id}, journey_{journey_id}, stage_{stage_id})"
            )
        return {}, None

    def get_agents_in_region(self, simulation_id, region):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        if len(region) < 3:
            return None, "region needs at least 3 points"
        ring = list(region)
        if ring[0] != ring[-1]:  # agents_in_polygon wants a closed ring
            ring.append(ring[0])
        agent_ids = simulation.agents_in_polygon(ring)
        return dict(agent_ids=agent_ids), None

    def get_desired_speed_of_agents(self, simulation_id, agent_ids):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        speeds = {}
        try:
            for agent_id in agent_ids:
                speeds[agent_id] = simulation.agent(agent_id).model.desired_speed
        except (RuntimeError, AttributeError) as e:
            return None, str(e)
        return dict(desired_speeds=speeds), None

    def set_desired_speed_of_agents(self, simulation_id, desired_speeds):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        try:
            for agent_id, speed in desired_speeds.items():
                simulation.agent(agent_id).model.desired_speed = speed
        except (RuntimeError, AttributeError) as e:
            return None, str(e)
        if (script := self._script(simulation_id)) is not None:
            script.write(*(
                f"simulation.agent(agent_{agent_id}).model.desired_speed = {speed!r}"
                for agent_id, speed in desired_speeds.items()
            ))
        return {}, None

    def add_journey(self, simulation_id, stage_ids):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        journey = jps.JourneyDescription(stage_ids=stage_ids)
        for i in range(1, len(stage_ids)):
            journey.set_transition_for_stage(stage_ids[i-1], jps.Transition.create_fixed_transition(stage_ids[i]))
        journey_id = simulation.add_journey(journey)
        self._journeys[journey_id] = simulation_id
        if (script := self._script(simulation_id)) is not None:
            stages = ", ".join(f"stage_{s}" for s in stage_ids)
            lines = [
                f"journey_description_{journey_id} = jps.JourneyDescription(stage_ids=[{stages}])"
            ]
            for i in range(1, len(stage_ids)):
                lines.append(
                    f"journey_description_{journey_id}"
                    f".set_transition_for_stage(stage_{stage_ids[i - 1]}, "
                    f"jps.Transition.create_fixed_transition("
                    f"stage_{stage_ids[i]}))"
                )
            lines.append(
                f"journey_{journey_id} = simulation.add_journey(journey_description_{journey_id})"
            )
            script.write(*lines)
        return dict(journey_id=journey_id), None

    def add_waypoint_stage(self, simulation_id, x, y, distance):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        waypoint_id = simulation.add_waypoint_stage((x, y), distance)
        self._stages[waypoint_id] = simulation_id
        if (script := self._script(simulation_id)) is not None:
            script.write(
                f"stage_{waypoint_id} = simulation.add_waypoint_stage(({x!r}, {y!r}), {distance!r})"
            )
        return dict(stage_id=waypoint_id), None

    def add_exit_stage(self, simulation_id, polygon):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        if len(polygon) < 3:
            return None, "exit polygon needs at least 3 points"
        stage_id = simulation.add_exit_stage(polygon)
        self._stages[stage_id] = simulation_id
        if (script := self._script(simulation_id)) is not None:
            script.write(
                f"stage_{stage_id} = simulation.add_exit_stage({polygon!r})"
            )
        return dict(stage_id=stage_id), None

    def add_waiting_set_stage(self, simulation_id, points):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        if len(points) < 1:
            return None, "waiting set needs at least 1 point"
        stage_id = simulation.add_waiting_set_stage(points)
        self._stages[stage_id] = simulation_id
        if (script := self._script(simulation_id)) is not None:
            script.write(
                f"stage_{stage_id} = simulation.add_waiting_set_stage({points!r})"
            )
        return dict(stage_id=stage_id), None

    def set_waiting_set_state(self, simulation_id, stage_id, state):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        jps_state = (
            jps.WaitingSetState.ACTIVE
            if state == jupedsim_pb2.ACTIVE
            else jps.WaitingSetState.INACTIVE
        )
        try:
            simulation.get_stage(stage_id).state = jps_state
        except (RuntimeError, AttributeError) as e:
            return None, str(e)
        if (script := self._script(simulation_id)) is not None:
            state_name = (
                "ACTIVE" if state == jupedsim_pb2.ACTIVE else "INACTIVE"
            )
            script.write(
                f"simulation.get_stage(stage_{stage_id}).state = jps.WaitingSetState.{state_name}"
            )
        return {}, None

    def get_waiting_set_state(self, simulation_id, stage_id):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        try:
            proxy = simulation.get_stage(stage_id)
            proto_state = (
                jupedsim_pb2.ACTIVE
                if proxy.state == jps.WaitingSetState.ACTIVE
                else jupedsim_pb2.INACTIVE
            )
            return dict(
                state=proto_state,
                count_waiting=proxy.count_waiting(),
                count_targeting=proxy.count_targeting(),
            ), None
        except (RuntimeError, AttributeError) as e:
            return None, str(e)

    def get_core_properties_of_all_agents(self, simulation_id):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        properties = {}
        for agent in simulation.agents():
            properties[agent.id] = jupedsim_pb2.AgentCoreProperties(
                position=jupedsim_pb2.Point(
                    x=agent.position[0], y=agent.position[1]
                ),
                orientation=jupedsim_pb2.Point(
                    x=agent.orientation[0], y=agent.orientation[1]
                ),
            )
        return dict(properties=properties), None

    def iterate(self, simulation_id, count=1):
        if (simulation := self._simulations.get(simulation_id, None)) is None:
            return None, f"simulation ID {simulation_id} unknown"
        if count < 1:
            count = 1
        if (script := self._script(simulation_id)) is not None:
            script.write(f"simulation.iterate(count={count})")
        simulation.iterate(count=count)
        return {}, None
