name: i18n

on:
  workflow_dispatch:

jobs:
  run_i18n_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Install gettext for translations
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Run script
        run: python ${{ github.workspace }}/tools/build_config/i18n.py

      - name: Pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update translatable strings ref #11859'
          title: 'Update gettext po files'
          add-paths: ${{ github.workspace }}/data/po/*.po
          draft: always-true
          base: main
          branch: sumo-patches
          signoff: true
          body: 'Collect translatable strings from gettext syntax inside the SUMO source code (auto-generated by Github Action).'
