name: Remove Docker Tag

on:
    push:
    workflow_dispatch:

jobs:
  remove-docker-tag:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    # (required)
    permissions:
      contents: read
      packages: write

    steps:
#    - name: Remove Docker Tag
#      uses: rafalkk/remove-dockertag-action@v1
#      with:
#        tag_name: dependabot-github_actions-docker-build-push-action-7
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        is_organization: true
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker pull ghcr.io/eclipse-sumo/sumo:v1_26_0
          docker run --name tmp-update ghcr.io/eclipse-sumo/sumo:v1_26_0 bash -c "rm apache-arrow-apt-source-latest-jammy.deb && wget https://packages.apache.org/artifactory/arrow/ubuntu/apache-arrow-apt-source-latest-jammy.deb && apt-get -qq -y install ./apache-arrow-apt-source-latest-jammy.deb && apt-get -qq update && apt-get -qq -y install libparquet2300"
          docker commit tmp-update ghcr.io/eclipse-sumo/sumo:1.26.0
          docker tag ghcr.io/eclipse-sumo/sumo:1.26.0 ghcr.io/eclipse-sumo/sumo:v1_26_0
          docker push ghcr.io/eclipse-sumo/sumo:1.26.0
          docker push ghcr.io/eclipse-sumo/sumo:v1_26_0
